### ISSUE TITLE
test TestModel fails

### ISSUE THREAD

**Issue by marcelloh** [fastschema/fastschema#11]
I found this when running : make testpkg

m.client = nil and should not be ;-)

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x58 pc=0x1012b93bc]

goroutine 147 [running]:
testing.tRunner.func1.2({0x1016283a0, 0x101c3d060})
	/usr/local/go/src/testing/testing.go:1631 +0x1c4
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1634 +0x33c
panic({0x1016283a0?, 0x101c3d060?})
	/usr/local/go/src/runtime/panic.go:770 +0x124
github.com/fastschema/fastschema/pkg/entdbadapter.(*Model).Query(0x140000ae780, {0x0, 0x0, 0x0})
	fastschema/pkg/entdbadapter/model.go:90 +0x5c
github.com/fastschema/fastschema/pkg/entdbadapter.TestModel(0x14000366d00)
	fastschema/pkg/entdbadapter/model_test.go:59 +0x35c
testing.tRunner(0x14000366d00, 0x1017197b8)
	/usr/local/go/src/testing/testing.go:1689 +0xec
created by testing.(*T).Run in goroutine 1
	/usr/local/go/src/testing/testing.go:1742 +0x318
```

**Comment by ngocphuongnb** [comment]
@marcelloh Thank you, the bug was fixed in this PR: https://github.com/fastschema/fastschema/pull/16
